### PR TITLE
Use spigot javadoc, closes #186

### LINKED ISSUE #186: jd.bukkit.org Links are broken
As jd.bukkit.org is offline, all the links are broken.

### PR DESCRIPTION
**Pull request by YukonAppleGeek**

### CODE REVIEW

**Comment by YukonAppleGeek** [comment]
@McSpider Made a pull request incase you want to use something else.

**Comment by McSpider** [comment]
No, this is fine, the only reason I haven't updated the links is because PGM isn't on 1.8 yet.
(The bukkit docs were for 1.7, while the spigot docs are for 1.8)

**Comment by YukonAppleGeek** [comment]
We are going to be moving to 1.8 soon and the names of things has not changed so it should be fine.

**Comment by McSpider** [comment]
There are several new materials, not sure if anything else was added.

**Pull request merged**
