### PR TITLE
Add Free-For-All to Other Gamemodes

### PR DESCRIPTION
**Pull request by matic0basle**

### CODE REVIEW

**Comment by Plastix** [comment]
We already have this documented. https://github.com/OvercastNetwork/docs.oc.tc/commit/c3199ad0fad24984b37ae3971179e45a64b20a11

**Comment by matic0basle** [comment]
That explains the players game setting not ffa it self. What I posted is under the Gamemodes tab where ffa isn't. I think it should be there as it is a gamemode and not a setting.

**Comment by AnthonyTag** [comment]
Ehh, I could see this being slightly useful, although I don't know how much of a necessity it is.

**Comment by McSpider** [comment]
Merged: a46b4e15134ce7549fb2434f0100925161398cc8

Thanks!

**Pull request closed without merging**
