### PR TITLE
Update map version from 1.3.5 to 1.3.7 on Harb

### PR DESCRIPTION
**Pull request by McFanta**

### CODE REVIEW

**Comment by McSpider** [comment]
I'm pretty sure that other things have changed in the XML besides the version string, if you want this to be merged please also provide those changes.

**Comment by McFanta** [comment]
Yeah I figured it out- The author names are not placed corectly. I'll fix that. Waiting for my pull requests to be merged ;)!

**Comment by McFanta** [comment]
I have changed every possible things and stuff in the xml Which you told me to do. Is it possible that you could merge my pull request now then @McSpider?

**Comment by CaptainElliott** [comment]
This really needs to me made 1 commit with an appropriate name before we can consider merging

**Comment by McFanta** [comment]
I have git but I didn't knew git were more useful. Need some help ;P

**Pull request closed without merging**
